#!/bin/bash

PATH=/usr/bin:/home/pi/wiringPi/gpio

echo "ATXRaspi shutdown script starting..."
echo "Asserting pins (7=in,low; 8=out,high)"

gpio -g mode 7 in
gpio -g write 7 0
gpio -g mode 8 out
gpio -g write 8 1

while [ 1 ]; do
  if [ "$(/home/pi/wiringPi/gpio/gpio -g read 7)" = "1" ]; then
    echo "PIN7 requested a SYSTEM HALT !"
    sudo poweroff
    break
  fi
  /bin/sleep 0.5
done

exit 0