#!/bin/bash

PATH=/usr/bin:/home/pi/wiringPi/gpio

echo "ATXRaspi shutdown script starting..."
echo "Asserting pins (7=in,low; 8=out,high)"

gpio -g mode 7 in
gpio -g write 7 down
gpio -g mode 8 out
gpio -g write 8 up

COUNTER=0

#while [ $COUNTER -lt 10 ]; do
while [ 1 ]; do
    #echo Looping - counter is $COUNTER
    #let COUNTER=COUNTER+1
    #sleep 1
    if [ "$(/home/pi/wiringPi/gpio/gpio -g read 7)" = "1" ]; then
        echo "PIN7 requested a SYSTEM HALT !"
        sudo halt
  break
    fi
    sudo sleep 0.5
done


exit 0
